name: Stage deploy

on:
  workflow_dispatch:
  push:
    branches:
      - stage

jobs:
  qa:
    name: QA
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: stage
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install node dependencies
        run: yarn install
      - name: Unit test
        run: yarn test
      - name: Lint
        run: yarn lint
